### Chi-Square Test

Association between Device Type and Customer Satisfaction

Background:
- Mizzare Corporation has collected data on customer satisfaction levels for two types of smart home devices: Smart Thermostats and Smart Lights. They want to determine if there's a significant association between the type of device purchased and the customer's satisfaction level.


In [1]:
## Import nesessary libraries
import pandas as pd
from scipy import stats

In [8]:
contigency_table_data = pd.read_csv("Contigency_table.csv")
contigency_table_data

Satisfaction  Smart Thermostat  Smart Light
0    Very Satisfied                50           70
1         Satisfied                80          100
2           Neutral                60           90
3       Unsatisfied                30           50
4  Very Unsatisfied                20           50

Step 1: State the hypotheses
- H0: There is no significant association between the type of smart home device purchased 
- H1: There is significant association between the type of smart home device purchased 

Step 2: Compute the Chi-Square Statistic

In [31]:
satis_smart_thermo = pd.crosstab(index = contigency_table_data['Smart Thermostat'],columns=contigency_table_data['Satisfaction'])

In [23]:
satis_smart_thermo

Satisfaction      Neutral  Satisfied  Unsatisfied  Very Satisfied  \
Smart Thermostat                                                    
20                      0          0            0               0   
30                      0          0            1               0   
50                      0          0            0               1   
60                      1          0            0               0   
80                      0          1            0               0   

Satisfaction      Very Unsatisfied  
Smart Thermostat                    
20                               1  
30                               0  
50                               0  
60                               0  
80                               0

In [32]:
chi2_value,p_value,deof,exp_freq = stats.chi2_contingency(observed=satis_smart_thermo)

In [33]:
print("Chi2_Value:",chi2_value)
print("p_Value:",p_value)
print("Degree of freedom:",deof)
print("Expected frequency:",exp_freq)

Chi2_Value: 20.000000000000004
p_Value: 0.2202206466016988
Degree of freedom: 16
Expected frequency: [[0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]]


Step 3: Determine the Critical Value
- Using the significance level (alpha) of 0.05 and the degrees of freedom (which is the number of categories minus 1)


In [28]:
## Calculate degree of freedom using (r-1)*(c-1)
# where,m = no of categories in one categorical feature 
#  n = no of categories in another categorical feature
# We have 4 categories in "Satisfaction" feature and 2 categories in another categorical variable
dof = (4-1)*(2-1)

alpha = 0.05

In [ ]:
## calculate critical value
critical_value = stats.chi2.ppf(1-alpha,dof)

np.float64(7.814727903251179)