In [25]:
import pandas as pd
from sklearn.feature_selection import RFE,SelectFromModel,chi2,SelectKBest
from sklearn.linear_model import LogisticRegression

### Read Data

In [4]:
diabetes_df = pd.read_csv('pima-indians-diabetes.data.csv')

In [9]:
filename = "pima-indians-diabetes.data.csv"
feature_name = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [12]:
datafarme = pd.read_csv(filename)
array = datafarme.values
array

array([[1.00e+00, 8.50e+01, 6.60e+01, ..., 3.51e-01, 3.10e+01, 0.00e+00],
       [8.00e+00, 1.83e+02, 6.40e+01, ..., 6.72e-01, 3.20e+01, 1.00e+00],
       [1.00e+00, 8.90e+01, 6.60e+01, ..., 1.67e-01, 2.10e+01, 0.00e+00],
       ...,
       [5.00e+00, 1.21e+02, 7.20e+01, ..., 2.45e-01, 3.00e+01, 0.00e+00],
       [1.00e+00, 1.26e+02, 6.00e+01, ..., 3.49e-01, 4.70e+01, 1.00e+00],
       [1.00e+00, 9.30e+01, 7.00e+01, ..., 3.15e-01, 2.30e+01, 0.00e+00]])

In [13]:
diabetes_df = pd.DataFrame(data = array,columns=feature_name)

In [14]:
diabetes_df.shape

(767, 9)

In [15]:
diabetes_df.head()

preg   plas  pres  skin   test  mass   pedi   age  class
0   1.0   85.0  66.0  29.0    0.0  26.6  0.351  31.0    0.0
1   8.0  183.0  64.0   0.0    0.0  23.3  0.672  32.0    1.0
2   1.0   89.0  66.0  23.0   94.0  28.1  0.167  21.0    0.0
3   0.0  137.0  40.0  35.0  168.0  43.1  2.288  33.0    1.0
4   5.0  116.0  74.0   0.0    0.0  25.6  0.201  30.0    0.0

In [7]:
diabetes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   6       767 non-null    int64  
 1   148     767 non-null    int64  
 2   72      767 non-null    int64  
 3   35      767 non-null    int64  
 4   0       767 non-null    int64  
 5   33.6    767 non-null    float64
 6   0.627   767 non-null    float64
 7   50      767 non-null    int64  
 8   1       767 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [17]:
diabetes_df.describe(include='all')

preg        plas        pres  ...        pedi         age       class
count  767.000000  767.000000  767.000000  ...  767.000000  767.000000  767.000000
mean     3.842243  120.859192   69.101695  ...    0.471674   33.219035    0.348110
std      3.370877   31.978468   19.368155  ...    0.331497   11.752296    0.476682
min      0.000000    0.000000    0.000000  ...    0.078000   21.000000    0.000000
25%      1.000000   99.000000   62.000000  ...    0.243500   24.000000    0.000000
50%      3.000000  117.000000   72.000000  ...    0.371000   29.000000    0.000000
75%      6.000000  140.000000   80.000000  ...    0.625000   41.000000    1.000000
max     17.000000  199.000000  122.000000  ...    2.420000   81.000000    1.000000

[8 rows x 9 columns]

#### Feature Selection using SelectKBest

In [19]:
x = diabetes_df.drop('class',axis =1)
y = diabetes_df['class']

In [22]:
model = SelectKBest(score_func=chi2,k=4)
fited_model = model.fit(x,y)

In [23]:
fited_model.scores_

array([ 110.72718168, 1406.59049075,   17.50499769,   51.00789486,
       2219.39781908,  127.67149145,    5.35636428,  178.01076049])

In [24]:
(fited_model.transform(x))

array([[ 85. ,   0. ,  26.6,  31. ],
       [183. ,   0. ,  23.3,  32. ],
       [ 89. ,  94. ,  28.1,  21. ],
       ...,
       [121. , 112. ,  26.2,  30. ],
       [126. ,   0. ,  30.1,  47. ],
       [ 93. ,   0. ,  30.4,  23. ]])

#### Feature selection using RFE(Recursive Forword Elimination)

In [31]:
log_model = LogisticRegression(max_iter=400)

In [32]:
RFE_model = RFE(estimator=log_model,n_features_to_select=3)

In [33]:
fit_rfe = RFE_model.fit(x,y)

In [34]:
fit_rfe.n_features_

np.int64(3)

In [35]:
fit_rfe.ranking_

array([1, 2, 4, 6, 5, 1, 1, 3])

In [37]:
pd.DataFrame({'columns':x.columns,'impotance':fit_rfe.ranking_})

columns  impotance
0    preg          1
1    plas          2
2    pres          4
3    skin          6
4    test          5
5    mass          1
6    pedi          1
7     age          3

#### Feture Selection using Select From Model

In [44]:
lod_model_2 =LogisticRegression(penalty='l2')

In [45]:
selector = SelectFromModel(estimator=lod_model_2,threshold='median')

In [46]:
selector.fit(x,y)

s:\DataScience\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


SelectFromModel(estimator=LogisticRegression(), threshold='median')

In [58]:
(selector.get_support())

array([ True,  True, False, False, False,  True,  True, False])