### Why numpy?
- Inorder to perform to numeric operations like array addition, multiplication,create dummy values etc
- It's quite faster than python when we are dealing with numerical operations

In [48]:
import numpy as np

In [49]:
arr_1=np.array([1,2,3,4,5,6,7])
arr_1

array([1, 2, 3, 4, 5, 6, 7])

In [50]:
type(arr_1)

numpy.ndarray

In [51]:
list1=[1,2,3,4,5,6,7]
list1

[1, 2, 3, 4, 5, 6, 7]

In [52]:
type(list1)

list

### List vs Numpy Array
- In List, we cannotdo element-twise operation directly, but in numpy array

In [54]:
arr_1d = np.array[1,2,3,4,5]
print(arr_1d)
print("Dimension of Array",)

TypeError: 'builtin_function_or_method' object is not subscriptable

### Create 2-D array

In [55]:
np.array([[1,2,3,4],[5,6,7]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [56]:
array_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(array_2d)
print("Dimension of array")

[[1 2 3 4]
 [5 6 7 8]]
Dimension of array


### Create 3-D array

In [57]:
array_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(array_3d)
print("Dimension of array: ",array_3d.ndim)
print("No of Elements: ",array_3d.size)
print("Max Element Index: ",array_3d.argmax())
print("Type of Element: ",array_3d.dtype)
print()

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimension of array:  3
No of Elements:  9
Max Element Index:  8
Type of Element:  int64



In [58]:
array_3d_float=array_3d.astype('float')


In [59]:
(array_3d_float).dtype

dtype('float64')

In [60]:
list1= str([1,2,3])
list1

'[1, 2, 3]'

### Conversion of list to array


In [62]:
list_array= list(array_3d)
list_array

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])]

In [63]:
type(list_array)

list

In [64]:
array_to_list =array_3d.tolist()
print(array_to_list)
print(type(array_to_list))

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]
<class 'list'>


### Statistical Operations

In [65]:
arr_6 = np.array([1,2,3,4,5,6,7,8,9,10])
arr_6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr_6.sum()

np.int64(55)

In [67]:
arr_6.prod()

np.int64(3628800)

In [68]:
arr_6.mean()

np.float64(5.5)

In [69]:
arr_6.std()

np.float64(2.8722813232690143)

In [70]:
arr_6.argmax()

np.int64(9)

In [71]:
arr_6.argmin()

np.int64(0)

### Reshaping

In [72]:
arr_7 = np.array([[1,2,3,4],[5,6,7,8]])
arr_7

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [73]:
print('Dimension: ',arr_7.ndim)
print("Shape: ",arr_7.shape)

Dimension:  2
Shape:  (2, 4)


In [74]:
arr_7_reshape = arr_7.reshape(4,2)
print(arr_7_reshape)
print('Dimension: ',arr_7_reshape.ndim)
print("Shape: ",arr_7_reshape.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Dimension:  2
Shape:  (4, 2)


In [75]:
arr_7_reshape = arr_7.reshape(1,8)
print(arr_7_reshape)
print('Dimension:',arr_7_reshape.ndim)
print("Shape:",arr_7_reshape.shape)

[[1 2 3 4 5 6 7 8]]
Dimension: 2
Shape: (1, 8)


In [76]:
arr_7_flatten = arr_7.flatten()
print(arr_7_flatten)
print('Dimension:',arr_7_flatten.ndim)
print("Shape:",arr_7_flatten.shape)

[1 2 3 4 5 6 7 8]
Dimension: 1
Shape: (8,)


### Sequencing, Repetiton and Random number generation

In [77]:
np.arange(1,21,dtype='int')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [78]:
np.arange(1,21,dtype='float')

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [79]:
np.linspace(start =1,stop=50,dtype='float',num=20)

array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
       13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
       26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
       39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ])

In [80]:
6.15789474 - 3.57894737 

2.57894737

In [81]:
np.linspace(1,10,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [82]:
np.ones((3,5),dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [83]:
np.ones((3,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [84]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [85]:
array_3d.repeat(repeats= 10,axis=0)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [86]:
### Generate random number
print(np.random.rand(5,5))   ##always be in range of 0 and 1

[[0.14441091 0.99955816 0.09767426 0.26152275 0.45241164]
 [0.44292526 0.73892353 0.87143903 0.55677401 0.08819362]
 [0.28282436 0.38225375 0.5278093  0.08573847 0.24837033]
 [0.02430507 0.13540062 0.3274503  0.11276615 0.11809461]
 [0.04216562 0.4599903  0.36493785 0.58835669 0.72306509]]


In [87]:
np.random.randint(low=1,high=100,size=(10,3))

array([[48, 15, 56],
       [95, 32, 42],
       [50, 45, 25],
       [64, 86, 20],
       [79, 26, 87],
       [54, 19, 25],
       [35, 58, 24],
       [51, 97, 74],
       [ 9, 10,  5],
       [43, 93, 10]], dtype=int32)

In [88]:
lotter_list = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a = lotter_list,size=1)

array([4])

### Explore where function in numpy